#! /bin/sh
# /etc/init.d/noip2

# Supplied by no-ip.com
# Modified for Debian GNU/Linux by Eivind L. Rygge <eivind@rygge.org>
# Updated by David Courtney to not use pidfile 130130 for Debian 6.
# Updated again by David Courtney to "LSBize" the script for Debian 7.

### BEGIN INIT INFO
# Provides:     noip
# Required-Start: networking
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Start noip at boot time
# Description: Start noip at boot time
### END INIT INFO

# . /etc/rc.d/init.d/functions  # uncomment/modify for your killproc

# DAEMON=/usr/local/bin/noip2
uname=#uname#
pwd=#pswd#
DAEMON="noip-duc -g moonbrew.ddns.net -u $uname -p $pwd"
DAEMON_NAME=noip
DAEMON_USER=root
PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

case "$1" in

    start)
    echo -n "Starting dynamic address update: "
    log_daemon_msg "Starting $DAEMON_NAME daemon"
    log_end_msg $?
    start-stop-daemon --start --exec $DAEMON
    ;;

    stop)
    echo -n "Shutting down dynamic address update:"
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    ;;

    restart)
    echo -n "Restarting dynamic address update: "
    start-stop-daemon --stop --oknodo --retry 30 --exec $DAEMON
    start-stop-daemon --start --exec $DAEMON
    ;;

    status)
    status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
    ;;

    *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1

esac
exit 0